name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-02"
compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMmQxYmYxYzEtYTNlZC00NDUyLWFiMWQtN2YyMjhlYTYyN2U3IiwidGVuYW50X2lkIjoiMWEzMmVmYmI1MjE0ODU1ODZjYzA5M2I0ODZmNmU1MWEyNzE0MmE4NGFkNGY2MmU0NDIzNTJkYjE5Y2QzMDZmNSIsImludGVybmFsX3NlY3JldCI6ImVmZWM0NTgwLWIzYWUtNDY3MC1hMjBiLTJlMWEzNDJkMjEwOSJ9.n-kSP5v4rxNw6ktDyZw5CU6yxO2shyLZaodRYHCIqsg"
JWT_SECRET = "mysecretpassword"